name: Pylint
on: [push]
jobs:
  Backend-Linter:
    runs-on: ubuntu-latest
    env:
        PYTHON_VERSION: "3.10.12"
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python $PYTHON_VERSION
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')






